### ISSUE TITLE
Sha256 checksum doesn't work correctly

### ISSUE THREAD

**Issue by augi** [avast/stor-client#10]
Today, so using version `1.1.5`, stor-cli downloaded file named `8b006d694ca25a29e4b9a2d983411fce8535375254c8db4a3c78aaf360acbac6` but the file is empty (we have much more files with the same issue).

The Sha256 checksum should IMHO refuse to accept this file. So maybe something is wrong with the Sha256 check.

**Comment by augi** [comment]
This issue became very frequent after update from `1.1.4` to `1.1.5` so maybe the problem is somewhere between these versions.

**Comment by JaSei** [comment]
Should be fixed by PR #11

**Comment by JaSei** [comment]
affected version 1.1.5
fixed by 2.0.0
